/**:
  controller_manager:
    ros__parameters:
      update_rate: 100
      
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  joint_state_broadcaster:
    ros__parameters: {}

  joint_trajectory_controller:
    ros__parameters:
      command_interfaces:
        - position
      
      state_interfaces:
        - position
        - velocity
      
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0

ur3e_1:
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - ur3e_1/shoulder_pan_joint
        - ur3e_1/shoulder_lift_joint
        - ur3e_1/elbow_joint
        - ur3e_1/wrist_1_joint
        - ur3e_1/wrist_2_joint
        - ur3e_1/wrist_3_joint

ur3e_2:
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - ur3e_2/shoulder_pan_joint
        - ur3e_2/shoulder_lift_joint
        - ur3e_2/elbow_joint
        - ur3e_2/wrist_1_joint
        - ur3e_2/wrist_2_joint
        - ur3e_2/wrist_3_joint